vinayakgavariya/PlaylistAdda

index.html
=> Updated index.html with a playlist

index.html, style.css
[Image](https://i.ibb.co/N61h092/Screenshot-2022-10-03-153540.png) 
=> Add css code which is present in html to style.css 

index.html
=> add new playlist

index.html
=> add card bowo

index.html, style.css
=> Added header,changed a bit of look and feel(background,hover etc.),better alignment

index.html
Hackoctober fest 2022
- added the playlist card
=> Haspdecrypted Playlist added

index.html, style.css
- Added search bar to search for playlist by either playlist name or author.
- Result: 
https://user-images.githubusercontent.com/91678228/193652129-748a0361-851c-47a5-92b0-97799b7c8770.mp4
Resolves #3
=> added search bar

index.html
=> Regime's commit

index.html
=> added a new playlist

.vscode/settings.json, index.html
=> fixed broken spotify links

style.css
=> Made navbar and searchbar ui better

index.html
=> added a playlist and fixed a typo

index.html
=> added playlist

index.html
=> Ishika's playlist index.html

index.html
- I've added my playist
- This is for Hacktoberfest 2022
Contribution to #8
=> Added my playlist

index.html, index.js
- Created a separate file for javascript code.
-  Transferred all the js code to index.js
- Provided the src as index.js and connected it to index.html
Resolves #30
Kindly merge this under hacktoberfest.
=> add separate javascript file

index.html
=> Add Playlist

index.html
=> my 1st contribution

index.html, style.css
#25 **Created a Youtube card**
- Added a card
- did css
- made it responsive
=> Adding Youtube --card

index.html
**Implemented Spritual Playlist**
=> Implemented Spritual Playlist

index.html, index.js, style.css
Reverts VG-1/PlaylistAdda#43
the reason I am doing revert because it has badly affected the mobile responsiveness of the site.
=> Revert "Added Dark Mode toggle button"

index.html, style.css
- Adding a header
- styling the youtube card
=> Styling the youtube card playlist

index.html, style.css
- Issue #53
- responsiveness card fix
=> Fixing the responsiveness of the youtube music player cards

index.html
=> Added my playlist 

index.html, style.css
Styled the navbar and search bar.
#68
=> Style Navbar & Search Bar

README.md
Added stars , forks , contributors in Readme page
- ...
- ...
- ...
=> add stars , forks , contributors count in readme

index.html
Please accept my PR. Thank you!
- ...
- ...
- ...
=> Added my playlist lofi love

index.html
=> Playlist added

index.html, style.css
added some style and made some enhancements in the code like making the logo clickable and changed the hover colour of the effect relevant to the playlist.
=> enhancements made in the code and gave header to playlists

index.html, style.css
=> Revert "enhancements made in the code and gave header to playlists"

index.html, index.js, style.css
=> Scroll bottom to top

index.html
taniaban2712 uploading new playlist
- I have updated my playlist with html
- I have stylized the website
=> uploading new playlist

contributing_es.md
- Add a new contributing.md file for Spanish speakers, this will allow Spanish speakers to contribute to the project.
- Graphical description of my change: 
Fixes #107
=> Added a new contributing.md file to allow Spanish speakers to contribute

index.html
=> Added my library

index.html
=> Added my playlist - Sarthak

index.html
=> Harshit Playlist

index.html
- Resolve Issue #113 
- Error
https://user-images.githubusercontent.com/82230512/195048769-0b1c347a-1a95-4bc1-8185-8435bebbdb77.mp4
-  After fixing Error
https://user-images.githubusercontent.com/82230512/195048662-ec6b8a8e-c43d-4a35-8f95-5ea5b37c840f.mp4
=> made proper alignment of cards

index.html
Add new YouTube Card you can see reference here please review it and merge my pull request.
=> Added new yt Card

index.html
=> Added new anime song playlist

index.html
Added a new YouTube section
Named **Chill Mood**
- ...
- ...
- ...
=> added new YouTube section

index.html
Added a playlist named "English Love Songs"
=> Added a playlist

index.html
=> fixed positons of the cards

index.html
=> My First commit

index.html
=> added 2nd playlist

index.html
Added a playlist called "Bollywood Unwind"
=> added bollywood-unwind

index.html
=> My First Comment- Nivesh Gaikwad

index.html
palak kumrawat
i have added my playlist of old songs
=> My first commit - palak kumrawat

index.html
=> My First Comment - Mohak Singhania

index.html
=> My First Commit - Kanishk Sharma

index.html
=> My First comment-Ameya Anil

index.html
=> Aman Prajapat

index.html
=> fixed broken links

index.html
=> Ashishk added his playlist.

index.html, style.css
Fixed the alignment of cards
-Cards were not placed correctly due to bugs in the code.
-Some div tags were not properly placed
-Fixed the cards and youtube section
`Fixes #173  `
=> fixed the alignment of div cards

index.html
=> Links updated

index.html
=> embed/playlist UPDATED LINKS

index.html
- Added my card-code playlist in the index.html file, and tested it.
- K-On!! Playlist by Sai Sunitha
- Screenshot below
=> Added my code in index.html

index.html
- Add new playlist card
- Embed apple music playlist
- Add new image and message to playlist
=> Add amit's playlist

index.html
This PR resolves Issue #193 by adding the required playlist.
=> This PR solves Issue #193

index.html
=> Added my Fav Playlist

index.html
=> I have added my Playlist

index.html
=> Added my favorite playlist.

index.html
Added a new Spotify Card "Taylor Swift Midnight Album 2022"
=> Added a New Card

index.html
=> successfully added a playlist by following all the rules

index.html
=> added soothing pop playlist for hactoberfest pr

index.html
=> akshatmishra25 added his playlist

index.html
@VG-1 I have fixed the styling of all the cards and separated the youtube and spotify cards.
In addition, I have also fixed some code by adding necessary closing tags
=> Fixed the display of all the cards as specified

style.css
This PR refers and resolves #210 , I have used webkit-scrollbar to _modify the scrollbar in the CSS file_ and and have tested this feature and have verified that **it is not a breaking change.**
=> Scrollbar customized

index.html, style.css
Fixes issue #207 
-> I have added the social media handles and newsletter and copyright section on footer.
-> if you find the changes good then pls merge my PR.
=> Have improve the footer of the website.

index.html
=> Updated the broken links and Fixed the allignment issue

index.html, style.css
Fixed the playlist card alignment by fixing the divs, added a specific height to the **title class** in _css so that all the cards look in alignment with each other_.
https://user-images.githubusercontent.com/70525647/197774996-70c199f0-41b2-44e0-b859-ef466e08d5b8.mp4
closes #227 
=> Alignment fixed

index.html
=> added my playlist and relevant info

index.html
#235 i have separated the youtube and spotify playlist
=> #235 issue - seprated youtube and spotify playlists successfully

index.html
#240 I have added my personal favourite playlist of Spotify and Youtube... 
Thank u  for letting me do that:)
=> #240 added my YouTube and Spotify Playlists

style.css
=> added custom scrollbar

index.html
=> hacktoberfest

index.html
@VG-1 I have add a new playlist "king playlist" in your website .please merge this .
=> add king playlist

index.html
=> Amazing DBZ Playlist was added.

index.html
=> playlist add

index.html
=> added tanishq's card
